import { NextResponse } from "next/server"
import { store } from "@/lib/store"
import { requireProjectAccess } from "@/lib/api-auth"
import { getUser, getRepo, getOrCreateRepo, createOrUpdateFile, commitFiles, createIssue, listIssues, parseRepoUrl, GitHubError } from "@/lib/github"

export async function POST(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params
  const access = await requireProjectAccess(id)
  if (!access.ok) return access.response

  const token = await store.getUserGithubToken(access.userId)
  if (!token) {
    return NextResponse.json({ error: "GitHub token is not configured. Add it in Settings → GitHub Integration." }, { status: 400 })
  }

  const body = await request.json().catch(() => ({}))
  const action = body.action || "push"
  const project = access.project

  try {
    const user = await getUser(token)
    const login = user.login
    const slugName = project.name.toLowerCase().replace(/[^a-z0-9_-]/g, "-").replace(/^-+|-+$/g, "").slice(0, 100)
    const linked = project.githubRepo ? parseRepoUrl(project.githubRepo) : null
    const isLinked = !!linked && !(linked.owner === login && linked.repo === slugName)

    if (action === "push") {
      let repo: { html_url: string; full_name: string }
      let created = false
      let owner = login
      let repoName = slugName

      if (linked) {
        owner = linked.owner
        repoName = linked.repo
        try {
          repo = await getRepo(token, owner, repoName)
        } catch (err) {
          if (err instanceof GitHubError && err.status === 404) {
            return NextResponse.json({ error: `Linked repository ${owner}/${repoName} was not found or your token has no access to it.` }, { status: 404 })
          }
          throw err
        }
      } else {
        const result = await getOrCreateRepo(token, login, slugName, project.description || "Created by Forge")
        repo = result.repo
        created = result.created
      }

      const artifacts = await store.getArtifacts(id)
      const tasks = await store.getTasks(id)

      const prd = artifacts.find((a) => a.type.toLowerCase() === "prd")
      const architecture = artifacts.find((a) => a.type.toLowerCase() === "architecture")
      const ux = artifacts.find((a) => a.type.toLowerCase() === "ux")
      const backlog = artifacts.find((a) => a.type.toLowerCase() === "backlog")

      const readmeParts = [`# ${project.name}`, project.description || "", "---"]
      if (prd) readmeParts.push("## Product Requirements Document", prd.content)
      if (architecture) readmeParts.push("## Architecture", architecture.content)
      if (ux) readmeParts.push("## UX Design", ux.content)
      if (backlog) readmeParts.push("## Backlog", backlog.content)

      const docsPath = isLinked ? "FORGE.md" : "README.md"
      await createOrUpdateFile(token, owner, repoName, docsPath, readmeParts.join("\n\n"), "chore: add project docs from Forge")

      const existingTitles = created
        ? new Set<string>()
        : new Set<string>((await listIssues(token, owner, repoName)).map((i: { title: string }) => i.title))

      let issuesCreated = 0
      for (const task of tasks) {
        if (existingTitles.has(task.title)) continue
        const labels = [task.priority === "p0" ? "priority:critical" : task.priority === "p1" ? "priority:high" : "priority:medium"]
        if (task.status === "in_progress") labels.push("status:in-progress")
        if (task.status === "done") labels.push("status:done")

        const issueBody = [
          task.description || "",
          "---",
          `**Story points:** ${task.storyPoints || "?"}`,
          `**Status:** ${task.status.replace("_", " ")}`,
        ].join("\n")

        await createIssue(token, owner, repoName, task.title, issueBody, labels)
        issuesCreated++
      }

      const codeFiles = await store.getCodeFiles(id)
      if (codeFiles.length > 0) {
        await commitFiles(
          token, owner, repoName,
          codeFiles.map((f) => ({ path: f.path, content: f.content })),
          "feat: app scaffold generated by Forge engineer agent"
        )
      }

      await store.updateProject(id, { githubRepo: repo.html_url })

      return NextResponse.json({
        repo: repo.html_url,
        fullName: repo.full_name,
        issuesCreated,
        message: created
          ? `Repository created at ${repo.html_url} with ${issuesCreated} issues.`
          : `Repository synced — ${issuesCreated} new issue${issuesCreated === 1 ? "" : "s"} added.`,
      })
    }

    if (action === "verify") {
      return NextResponse.json({ login: user.login, name: user.name, avatar: user.avatar_url })
    }

    return NextResponse.json({ error: "Unknown action" }, { status: 400 })
  } catch (err) {
    if (err instanceof GitHubError) {
      return NextResponse.json({ error: `GitHub error: ${err.message}` }, { status: err.status })
    }
    console.error("GitHub push error:", err)
    return NextResponse.json({ error: "Failed to push to GitHub" }, { status: 500 })
  }
}
